AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: This is a lambda service that returns weekdays given to points in time
  as parameters
Resources:
  GetWeekdaysFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: Weekdays::Weekdays.LambdaEntryPoint::FunctionHandlerAsync
      Runtime: dotnetcore3.1
      CodeUri: s3://weekdayscfs3bucket/4ce448f792e0ea2f4793e70fae93a128
      Policies:
      - AmazonDynamoDBFullAccess
      Timeout: 60
      MemorySize: 3008
      Environment:
        Variables:
          S3_BUCKET: weekdayscfsambucket
      Events:
        ProxyResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: Name
        AttributeType: S
      - AttributeName: Date
        AttributeType: S
      KeySchema:
      - AttributeName: Name
        KeyType: HASH
      - AttributeName: Date
        KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: '5'
        WriteCapacityUnits: '5'
      TableName: Holiday
